```{r Install Libs}
devtools::install_github("hadley/emo")
devtools::install_github("lchiffon/wordcloud2")
install.packages("syuzhet")
install.packages("tidyverse")
install.packages("lubridate")
install.packages("tm")
install.packages("devtools")
install.packages("ggthemes")
install.packages("extrafont")
install.packages("scales")
```

```{r Libs, include=FALSE}
library(syuzhet)
library(readr)
library(tidyverse)
library(lubridate)
library(tm)
library(emo)
library(ggthemes)
library(extrafont)
library(wordcloud2)
library(scales)
```

```{r Import Tweets, include=FALSE}
#font_import()
#loadfonts(device = "win")

#Import entire database of tweets
cleaned_tweets <- read_csv("D:/Faculdade/TCC e IC/cleaned_tweets.csv")

#only part of the base, for testing
cleaned_tweets <- slice_sample(cleaned_tweets, n = 10000, replace = FALSE)

# # of lines
N <- length(cleaned_tweets$created_at)
```

```{r include=FALSE}
#Top emojis used
emojis <- cleaned_tweets %>%
  mutate(emoji = ji_extract_all(cleaned_tweets$full_text)) %>%
  unnest(cols = c(emoji)) %>%
  count(emoji, sort = TRUE) %>%
  na.omit() %>%
  top_n(10)
```

```{r Frequency of Words}
# create corpus
corpus = Corpus(VectorSource(cleaned_tweets$full_text))
# create term-document matrix
tdm = TermDocumentMatrix(corpus)
# convert as matrix
tdm = as.matrix(tdm)

m <- as.matrix(tdm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
#head(d, 300)
```

```{r Extract Sentiments, include=FALSE}
#extracts the feeling of every word from the tweet from Saif Mohammad's NRC Emotion lexicon
sentiment <- get_nrc_sentiment(cleaned_tweets$full_text, language = "portuguese")
```

```{r formatting dataframe}
#rename columns with portuguese words of sentiments
sentiment <- sentiment %>% 
  rename(
    Raiva = anger,
    Ansiedade = anticipation,
    Nojo = disgust, 
    Medo = fear,
    Alegria = joy,
    Tristeza = sadness, 
    Surpresa = surprise, 
    Esperanca = trust,
    Negativo = negative, 
    Positivo = positive
  )

#dataframe of the tweet date + the extraction of emotions
sentiment_dt <- bind_cols(cleaned_tweets[,"created_at"],sentiment)
```

```{r general analysis, include=FALSE}
#transpose sentiment to list the emotions by rows
sentiment_transp<-data.frame(t(sentiment))

#sum total of sentiments
sentiment_sum <- data.frame(sort(rowSums(sentiment_transp),decreasing=TRUE))

#rename column
sentiment_sum <- sentiment_sum %>% 
  rename(
    Soma = sort.rowSums.sentiment_transp...decreasing...TRUE.
  )
#add 1 colunm with name of sentiment
sentiment_sum <- cbind("Sentimento" = rownames(sentiment_sum), sentiment_sum)

# count of sentiments
count_sentiment <- sentiment_sum[3:10,]

# count of positive and negative
count_pos_neg <- sentiment_sum[1:2,]

x <- apply(count_pos_neg[2],2,sum)
count_pos_neg$total <- x 

count_pos_neg <- count_pos_neg %>%
mutate(across(.cols = Soma:total, ~ round(.x/total*100,2))) 

count_pos_neg$total <- NULL

```

```{r Just Sentiments per month, include=FALSE}
#Just sentiments
#grouping the months of the dataframe with the sum of emotions divided by month and by emotion
sentiment_month <- sentiment_dt %>% 
  group_by(mes = month(created_at, label = TRUE, abbr = TRUE)) %>% 
  summarise(across(.cols = Raiva:Esperanca, sum))

#total sum of feelings, divided by month
x <- apply(sentiment_month[,2:9],1,sum)
sentiment_month$total <- x 

#dividing the total by the partials, to find the proportional value of each sentiment
sentiment_month_prop <- sentiment_month %>%
  mutate(across(.cols = Raiva:Esperanca, ~ round(.x/total*100,2))) 

#drop total column
sentiment_month_prop$total <- NULL
  
#database on longer format for chart
sentiment_month_longer <- pivot_longer(sentiment_month_prop, Raiva:Esperanca)

#Rename column
sentiment_month_longer <- sentiment_month_longer %>% 
  rename(
    Sentimento = name
  )
```

```{r just pos and neg per month}
#Just positive and negative
#grouping the dataframe months together with the sum of positive and negative
pos_neg_month <- sentiment_dt %>% 
  group_by(mes = month(created_at, label = TRUE, abbr = TRUE)) %>% 
  summarise(across(.cols = Negativo:Positivo, sum))

#total sum of feelings, divided by month
x <- apply(pos_neg_month[,2:3],1,sum)
pos_neg_month$total <- x 

#dividing the total by the partials, to find the proportional value of each sentiment
pos_neg_month_prop <- pos_neg_month %>%
  mutate(across(.cols = Negativo:Positivo, ~ round(.x/total*100,2))) 

#drop total column
pos_neg_month_prop$total <- NULL

#database on longer format for chart
pos_neg_month_longer <- pivot_longer(pos_neg_month_prop, Negativo:Positivo)

#Rename column
pos_neg_month_longer <- pos_neg_month_longer %>% 
  rename(
    Sentimento = name
  )
```


```{r Graphics}
#line plot sentiment
colors <- c("#FFC213","#2AB101","#179D8B","#090b7a","#0F4132","#900000","#FF3CC6","#8B3B79","#FED8B3","#B8F9A2")

#Line plot per month
g <- ggplot(sentiment_month_longer) + 
  aes(x=mes, y=value, color=Sentimento, group=Sentimento) + 
  geom_line() + 
  geom_point() +
  labs(title = "Proporção de Tweets em Cada Sentimento por Mês",
       x = "Mês",
       y = "Percentual",
       color = "Sentimento")+
  theme(axis.title = element_text())+
  scale_colour_manual(values=colors)+
  theme_fivethirtyeight()

#Export chart
ggsave("D:/Faculdade/TCC e IC/Imagens/Proporção de Tweets em Cada Sentimento por Mês.png", g)

#line plot positive and negative
g<- ggplot(pos_neg_month_longer) + 
  aes(x=mes, y=value, color=Sentimento, group=Sentimento) + 
  geom_line(data = subset(pos_neg_month_longer, Sentimento =="Negativo")) + 
  geom_point(data = subset(pos_neg_month_longer, Sentimento =="Negativo"))+
  labs(title = "Tweets Negativos por Mês",
       x = "Mês",
       y = "Percentual",
       color = "Sentimento")+
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  scale_colour_manual(values="#900000")

#Export chart
ggsave("D:/Faculdade/TCC e IC/Imagens/Tweets Negativos por Mês.png", g)

#bar plot with summarise of sentiments
g<- ggplot(count_sentiment)+
  aes(x=reorder(Sentimento,Soma), y=Soma, fill = Sentimento)+
  coord_flip()+
  geom_col()+
  labs(title = "Número Absoluto de Tweets em Cada Sentimento",
       subtitle = "Período: 2020",
       x = NULL,
       y = "Quantidade",
       color = "Sentimento")+
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  scale_fill_manual(values=colors)

#Export chart
ggsave("D:/Faculdade/TCC e IC/Imagens/Número Absoluto de Tweets em Cada Sentimento.png", g)

#pie chart of negative and positive sentiments
g <- ggplot(count_pos_neg)+
  aes(x="", y=Soma, fill = Sentimento)+
  geom_bar(stat="identity", width=1, color="white")+
  labs(title = "Percentual de Tweets Positivos e Negativos",
       subtitle = "Período: 2020",
       x = NULL,
       y = NULL,
     color = "Sentimento")+
  coord_polar("y", start=0)+
  geom_text(aes(y = Soma, label = Soma), color = "white", size=6, position = position_stack(vjust = 0.5))+
  scale_fill_manual(values=c("#090b7a","#900000"))+
  theme(axis.title = element_text())+
  theme_fivethirtyeight() + 
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())

#Export chart
ggsave("D:/Faculdade/TCC e IC/Imagens/Percentual de Tweets Positivos e Negativos.png", g)

#Bar plot with 10 common emojis in database 
g <- ggplot(emojis)+
  aes(x=reorder(emoji,-n), y=n, fill = emoji)+
  geom_col()+
  labs(title = "Emojis mais Frequentes em Números Absolutos",
       subtitle = "Período: 2020",
       x = NULL,
       y = NULL,
       color = "Sentimento")+
  theme(legend.text=element_text(size=30))+
  theme_fivethirtyeight()+
  scale_fill_manual(values=colors)+
  theme(axis.text = element_blank())

#Export chart
ggsave("D:/Faculdade/TCC e IC/Imagens/Emojis mais Frequentes em Números Absolutos.png", g)

#Word cloud 
#wordcloud(words = d$word, freq = d$freq, max.words = 300, scale=c(4,.5), random.order = FALSE, color=colors_wc)
wordcloud2(data = d[1:170,], size = 0.6, minRotation = -pi/100, maxRotation = pi/100, color = 'random-dark')

```

